version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: booksdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - thedb-network

  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=booksdb
    depends_on:
      - db
    networks:
      - thedb-network

volumes:
  db_data:

networks:
  thedb-network:
